kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: iamuser-eks-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]